version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eit_intermodular
    container_name: eit_intermodular
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "5050:1950"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: eit_intermodular
    #   MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3307"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "5051:1950"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  dbdata:
