version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eit_intermodular
    container_name: eit_intermodular
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravelapp:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - ./laravelapp:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: eit_intermodular
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "5051:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  dbdata:
