name: Build and publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rogerorti
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build image
        run: docker build -t rogerorti/eit_intermodular:latest -f dockerfile .

      - name: push image to docker hub
        run: docker push rogerorti/eit_intermodular:latest
