name: Notificar via email que s'ha fet push en el main

on:
  push:
    branches:
      - main

jobs:
  notify-by-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Nou push a main del projecte Laravel"
          body:
            S'ha fet un push a la branca main. Revisa els canvis en el Github.
          
          to:
            rortim2223@politecnics.barcelona
  
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
